# Generated by Django 5.2.7 on 2025-10-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('is_online', models.BooleanField(default=False)),
                ('is_broken', models.BooleanField(default=False)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('last_order', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='xy_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('shbh', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('provider', models.CharField(db_index=True, default='xy', max_length=50)),
                ('source_order_no', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('machine_number', models.CharField(db_index=True, max_length=100)),
                ('product_name', models.CharField(default='Unknown', max_length=255)),
                ('slot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_time', models.DateTimeField(db_index=True)),
                ('payment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_status', models.CharField(default='paid', max_length=20)),
                ('delivery_state', models.CharField(blank=True, max_length=64, null=True)),
                ('source_payload', models.JSONField(blank=True, null=True)),
                ('sync_status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('sync_endpoint', models.CharField(default='orders-receiver', max_length=255)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'source_order_no'], name='data_order_provide_11f330_idx'), models.Index(fields=['payment_time'], name='data_order_payment_4d21ba_idx'), models.Index(fields=['sync_status'], name='data_order_sync_st_aae494_idx')],
            },
        ),
    ]
