# Generated by Django 5.2.7 on 2025-10-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_machine_xy_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='machine_number',
        ),
        migrations.AddField(
            model_name='order',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.machine'),
        ),
    ]
